apiVersion: v1
data:
  tls.%s.crt:
%s
  tls.%s.key:
%s
  tls.%s.pw:
%s
  ca.crt:
%s
kind: Secret
metadata:
  name: qdr-internal-cert
  ownerReferences:
  - apiVersion: v1
    kind: Service
    name: messaging
type: kubernetes.io/tls